---
- hosts: webservers
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  tasks:
    - name: Update the repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Install Python3-pip
      apt:
         name: python3-pip
         state: present
         
    - name: Install flask using 'pip3' executable
      ansible.builtin.pip:
        name: flask
        executable: pip3
        state: latest

    - name: Upload the application to the servers
      copy:
        src: ./service.py
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Run the application
      shell: python3 /home/ubuntu/service.py
      async: 3600
      poll: 0
      
    - name: Install the snmpdaemon
      apt:
              name: snmpd
              state: latest
    
    - name: Copy the snmpd config file
      ansible.builtin.copy:
              src: ./snmpd.conf
              dest: /etc/snmp/snmpd.conf

    - name: Run the snmpdaemon
      service:
              name: snmpd
              state: restarted 


- hosts: proxy
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installing NGINX 
      apt:
        name: nginx
        state: present

    - name: uploading NGINX configuration file
      ansible.builtin.template:
        src: ./nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Restarting NGINX
      service:
        name: nginx
        state: restarted

- hosts: bastion
  any_errors_fatal: true
  gather_facts: yes
  become: yes
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Python3-pip
      apt:
         name: python3-pip
         state: present
         
    - name: Install required modules
      ansible.builtin.pip:
        name: [ 'flask', 'ping3' ]
        executable: pip3
        state: latest

    - name: Uploading the alive.py application
      copy:
        src: ./alive.py
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Copy nodes.yaml
      ansible.builtin.copy:
              src: ./nodes.yaml
              dest: /home/ubuntu

    - name: Running the application
      shell: python3 /home/ubuntu/alive.py
      async: 3600
      poll: 0


