---

- hosts: all
  gather_facts: yes
  become: yes

    
  tasks:
    - name: apt update
      apt:
        update_cache: true

- name: Configuring HAproxy as a loadbalancer
  hosts: HAproxy
  become: yes
  
