---

- hosts: all
  gather_facts: yes
  become: yes

    
  tasks:
    - name: apt update
      apt:
        update_cache: true

- name: Configuring HAproxy as a loadbalancer
  hosts: HAproxy
  become: yes
  
  tasks:

    
    - name : sudo wait
      become: yes
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
